<?
$PERM["bitrix"]["8"]="R";
$PERM["bitrix"]["*"]="D";
$PERM["services"]["8"]="W";
$PERM["services"]["5"]="W";
$PERM["seller"]["8"]="W";
$PERM["seller"]["7"]="R";
$PERM["seller"]["*"]="D";
$PERM["buyer"]["8"]="W";
$PERM["buyer"]["6"]="R";
$PERM["buyer"]["*"]="D";
$PERM["announcements"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>